version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
python:
  install:
    - path: .
    - requirements: docs/requirements.txt
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
