#!/usr/bin/env python

import json
import sys
import codecs

from csvkit import CSVKitReader
from csvkit.cli import CSVKitUtility

class CSVJSON(CSVKitUtility):
    """
    Convert CSV into JSON.
    """
    def add_arguments(self):
        self.argparser.add_argument('-i', '--indent', dest='indent', type=int, default=None,
            help='Indent the output JSON this many spaces. Disabled by default.')

    def main(self):
        """
        Convert CSV to JSON. 
        """
        rows = CSVKitReader(self.args.file, **self.reader_kwargs)
        column_names = rows.next()

	stream = codecs.getwriter('utf8')(sys.stdout)

        output = [dict(zip(column_names, row)) for row in rows]

        json.dump(output, stream, ensure_ascii=False, indent=self.args.indent, encoding='utf-8')

if __name__ == "__main__":
    utility = CSVJSON()
    utility.main()

