#!/usr/bin/env python

from csvkit import init_common_parser, extract_csv_reader_kwargs
from csvkit import sql
from csvkit import table

def main(args):
    """
    Generate a SQL create table statement for a given CSV file.
    """
    tab = table.Table.from_csv(args.file, **extract_csv_reader_kwargs(args))

    print sql.make_create_table_statement(tab, dialect=args.dialect)

if __name__ == '__main__':
    parser = init_common_parser(description='Generate a SQL CREATE TABLE statement for a CSV file.')
    parser.add_argument('-i', '--dialect', dest='dialect', choices=sql.DIALECTS,
                        help='Dialect of SQL to generate.')

    main(parser.parse_args())
