#!/usr/bin/env python

import csv
import sys

from csvkit import init_common_parser
from csvkit import sql
from csvkit import typeinference

def main():
    parser = init_common_parser(description='Generate a SQL CREATE TABLE statement for a CSV file.')
    parser.add_argument('-i', '--dialect', dest='dialect', choices=sql.DIALECTS,
                        help='Dialect of SQL to generate.')

    args = parser.parse_args()
    
    if args.tabs:
        args.delimiter = '\t'

    reader = csv.reader(args.file, delimiter=args.delimiter, quotechar=args.quotechar)

    column_names = reader.next()

    normal_types, normal_columns = typeinference.normalize_table(reader,len(column_names))
    print sql.make_create_table_statement(column_names, normal_types, normal_columns, dialect=args.dialect)

if __name__ == '__main__':
    main()
